language: generic

dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
      - libglu1-mesa

env:
  global:
    - INSTALL_EDM_VERSION=1.9.1
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - os: linux
      env: RUNTIME=2.7 ETS_TOOLKIT=qt4 VTK=8
    - os: linux
      env: RUNTIME=2.7 ETS_TOOLKIT=wx VTK=8
    - os: linux
      env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=8
    - os: osx
      env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=8
    - os: osx
      env: RUNTIME=2.7 ETS_TOOLKIT=qt4 VTK=7

cache:
  directories:
    - $HOME/.cache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - export DISPLAY=:99.0
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./ci/install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./ci/install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install --version ${RUNTIME} -y wheel numpy nose mock Sphinx coverage psutil

install:
  - if [[ ${ETS_TOOLKIT} == 'wx' ]]; then edm install -y wxpython; fi
  - if [[ ${ETS_TOOLKIT} == 'qt4' && ${RUNTIME} == '2.7' ]]; then edm install -y pyside; fi
  - if [[ ${ETS_TOOLKIT} == 'qt4' && ${RUNTIME} == '3.6' ]]; then edm run -- pip install "pyqt5==5.10.1"; fi
  - edm run -- pip install -r ci/ci-requirements.txt
  - if [[ ${VTK} == '8' ]]; then edm install -y vtk^=8 ; fi
  - if [[ ${VTK} == '7' ]]; then edm install -y vtk^=7 ; fi
  - edm run -- python -c "import vtk; print(vtk.vtkVersion.GetVTKSourceVersion())"
  - edm run -- python setup.py develop

script:
  - edm run -- coverage erase
  - edm run -- coverage run -p -m nose.core -v tvtk/tests
  - edm run -- coverage run -p -m nose.core -v mayavi
  #- if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then sh ci/travis-run-integration-tests.sh; fi
  - edm run -- coverage combine

after_success:
  - edm run -- pip install codecov
  - edm run -- codecov
