language: generic

dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
      - libglu1-mesa

env:
  global:
    - INSTALL_EDM_VERSION=2.0.0
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - os: linux
      env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=7
    - os: linux
      env: RUNTIME=3.6 ETS_TOOLKIT=qt4 VTK=8

cache:
  directories:
    - $HOME/.cache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./ci/install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - edm install --version ${RUNTIME} -y wheel numpy nose Sphinx coverage psutil

install:
  - if [[ ${ETS_TOOLKIT} == 'wx' ]]; then edm install -y wxpython; fi
  - if [[ ${ETS_TOOLKIT} == 'qt4' && ${RUNTIME} == '3.6' ]]; then edm run -- pip install "pyqt5==5.10.1"; fi
  - if [[ ${TRAVIS_EVENT_TYPE} == "cron" ]] ; then
        edm run -- pip install -r ci/ci-src-requirements.txt ;
    else
        edm run -- pip install -r ci/ci-requirements.txt ;
    fi;
  - if [[ ${VTK} == '8' ]]; then edm run -- pip install vtk; fi
  - if [[ ${VTK} != '8' ]]; then edm install -y vtk==7.0.0-3; fi
  - edm run -- python -c "import vtk; print(vtk.vtkVersion.GetVTKSourceVersion())"
  - edm run -- python setup.py develop

script:
  - edm run -- coverage erase
  - edm run -- coverage run -p -m nose.core -v tvtk/tests
  - edm run -- coverage run -p -m nose.core -v mayavi
  - edm run -- coverage combine

after_success:
  - edm run -- pip install codecov
  - edm run -- codecov
