name: pip_install_mayavi
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  pip_install_mayavi:
    strategy:
     matrix:
       os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
       python-version: [3.8]  # [2.7, 3.5, 3.6, 3.7, 3.8, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install numpy vtk
      - run: pip install mayavi
